# Generated by Django 3.0.8 on 2021-02-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='status_id',
            new_name='status',
        ),
    ]
